dtype: bfloat16
flux_fill_path: /content/ckpt/FLUX.1-Fill-dev
flux_redux_path: /content/ckpt/FLUX.1-Redux-dev
model:
  add_cond_attn: false
  latent_lora: false
  union_cond_attn: true
train:
  accumulate_grad_batches: 1
  base_dir: "/content/drive/MyDrive/[\u1107\u116E\u11AF\u1105\u1163\u11BC\u1112\u1165\
    \u11AB\u1110\u1165\u1109\u1173] \u1100\u116A\u11BC\u1100\u1169 \u110B\u1175\u1106\
    \u1175\u110C\u1175 \u1110\u1166\u11A8\u1109\u1173\u1110\u1173 \u1107\u116E\u11AF\
    \u1105\u1163\u11BC \u1100\u1161\u11B7\u110C\u1175 \u1109\u1175\u1109\u1173\u1110\
    \u1166\u11B7/Dataset/phase2/"
  batch_size: 8
  csv_path: "/content/drive/MyDrive/[\u1107\u116E\u11AF\u1105\u1163\u11BC\u1112\u1165\
    \u11AB\u1110\u1165\u1109\u1173] \u1100\u116A\u11BC\u1100\u1169 \u110B\u1175\u1106\
    \u1175\u110C\u1175 \u1110\u1166\u11A8\u1109\u1173\u1110\u1173 \u1107\u116E\u11AF\
    \u1105\u1163\u11BC \u1100\u1161\u11B7\u110C\u1175 \u1109\u1175\u1109\u1173\u1110\
    \u1166\u11B7/Dataset/phase2/phase2_train_nobom.csv"
  dataloader_workers: 5
  gradient_checkpointing: true
  lora_config:
    init_lora_weights: gaussian
    lora_alpha: 256
    r: 256
    target_modules: (.*x_embedder|.*(?<!single_)transformer_blocks\.[0-9]+\.norm1\.linear|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_k|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_q|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_v|.*(?<!single_)transformer_blocks\.[0-9]+\.attn\.to_out\.0|.*(?<!single_)transformer_blocks\.[0-9]+\.ff\.net\.2|.*single_transformer_blocks\.[0-9]+\.norm\.linear|.*single_transformer_blocks\.[0-9]+\.proj_mlp|.*single_transformer_blocks\.[0-9]+\.proj_out|.*single_transformer_blocks\.[0-9]+\.attn.to_k|.*single_transformer_blocks\.[0-9]+\.attn.to_q|.*single_transformer_blocks\.[0-9]+\.attn.to_v|.*single_transformer_blocks\.[0-9]+\.attn.to_out)
  max_steps: -1
  optimizer:
    params:
      lr: 1
      safeguard_warmup: true
      use_bias_correction: true
      weight_decay: 0.01
    type: Prodigy
  sample_interval: 500
  save_interval: 500
  save_path: runs
